baseurl: ''
url: 'https://gemz.ro'
dev_url: 'https://gemz.cszr.dev'
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
permalink: pretty
title: 'Gemz.ro — Shop smart, shop local'
short_title: 'Gemz.ro'
language: "ro"
lang_direction: "ltr"
background-color: "#f12705"
theme-color: "#f0f5ee"

google_analytics_id: "H2HMEBZC25" # without the G-
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "64px"
footer:
  copyright_text: 'built by <a class="nhg" href="https://nhg.design">nhg.design</a>'

seo:
  meta_og_title: "Gemz.ro — Shop smart, shop local"
  meta_og_type: "website"
  meta_og_url: "https://gemz.ro"
  meta_og_image: "images/social/og_metatag.png"
  meta_og_description: "Producători locali și business-uri din România într-o singură pagină web. Selectează locația ta și descoperă toate business-urile locale din zona ta."
  meta_twitter_card: "images/social/og_metatag.png"
  meta_twitter_site: "https://gemz.ro"
  meta_twitter_creator: "@gemz.ro"

markdown: kramdown

collections:
  shops:
    output: true
    permalink: /shops/:path
  team:
    output: true
  categories:
    output: true

sass:
  indentWidth: 4
  style: compressed # possible values: nested expanded compact compressed
  precision: 10

feed:
  path: "/atom.xml"
  collections:
    shops:
      path: "/feed.xml"

plugins:
  - jekyll-environment-variables
  - jekyll-menus
  - jekyll-feed
